import App from './components/App.svelte';
import Clapp from './components/Clapp.svelte';
import DeviceList from './components/DeviceList.svelte';
import DeviceEdit from './components/DeviceEdit.svelte';
import DeviceNew from './components/DeviceNew.svelte';
import DeviceDetails from './components/DeviceDetails.svelte';
import PersonList from './components/PersonList.svelte';
import PersonEdit from './components/PersonEdit.svelte';
import PersonNew from './components/PersonNew.svelte';